version: "3.9"

services:
  editor-bi:
    build: .
    container_name: editor-bi
    env_file:
      - .env
    ports:
      - "3010:3000"   # ðŸ‘ˆ HOST:3010 â†’ CONTAINER:3000
    restart: unless-stopped
